name: Generate index.html

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1.7.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}
          repositories: jjwl
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: wenn/jjwl
          token: ${{ steps.generate-token.outputs.token }}
          ref: main
      - name: Generate
        run: |
          #!/bin/bash
          set -e
          make

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          if ! git diff --cached --quiet; then
            git commit -m 'Update index.html'
            git push
          else
            echo "No changes to commit"
          fi
